import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import TopNavbar from "@/components/Homepage/TopNavbar";
import Navbar from "@/components/Homepage/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider enableSystem={false} attribute="class">
                    <TopNavbar />
                    <Navbar />
                    <div className="dark:bg-primary">{children}</div>
                </ThemeProvider>
            </body>
        </html>
    );
}
